version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - mongodb
      - rabbitmq
      - redis
  mongodb:
    # pull image from docker hub
    image: mongo
    # container name
    container_name: nestmongo
    # always restart the container if it stops.
    restart: always
    # database credentials, this is take value from env file
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    # database port
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 5672:5672
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
